
IMPORT_HELPER = {
    "python": [
        "import math",
        "import re",
        "import sys",
        "import copy",
        "import datetime",
        "import itertools",
        "import collections",
        "import heapq",
        "import statistics",
        "import functools",
        "import hashlib",
        "import numpy",
        "import string",
        "from typing import *",
        "from collections import *",
        "from statistics import median",
        "from functools import reduce",
        "import json",
        "from math import sqrt, ceil, floor, isqrt",
        "from collections import defaultdict",
        "from typing import Optional, List, Tuple",
        "import ast",
    ],
    "C++"   : [
        "#include <limits>",
        "#include <functional>",
        # "#include <json/json.h>",
        "#include <regex>",
        "#include <bitset>",
        "#include<stdlib.h>",
        "#include <cctype>",
        "#include<assert.h>",
        "#include <string.h>",
        "#include <cstdio>",
        "#include <iterator>",
        "#include <algorithm>",
        "#include <fstream>",
        "#include <cstring>",
        "#include<vector>",
        "#include<algorithm>",
        "#include <utility>",
        "#include <climits>",
        "#include <cstdlib>",
        "#include <iomanip>",
        "#include<map>",
        "#include <limits.h>",
        "#include<stdio.h>",
        "#include <deque>",
        "#include <stdlib.h>",
        "#include <cmath>",
        "#include<math.h>",
        "#include <cstdint>",
        "#include <unordered_map>",
        "#include <iostream>",
        # "#include <nlohmann/json.hpp>",
        "#include <map>",
        "#include <tuple>",
        "#include <numeric>",
        "#include <variant>",
        "#include <string>",
        "#include <set>",
        "#include<string>",
        "#include <stdexcept>",
        # "#include <cjson/cJSON.h>",
        "#include <exception>",
        "#include <optional>",
        "#include<iostream>",
        "#include <cerrno>",
        "#include <sstream>",
    ],
    "Java"  : [ 
        "import java.util.Map;",
        "import java.util.stream.Collectors;",
        "import java.util.Optional;",
        "import com.google.gson.Gson;",
        "import java.util.stream.IntStream;",
        "import java.io.BufferedReader;",
        "import java.util.List;",
        "import com.google.gson.JsonArray;",
        "import java.io.InputStreamReader;",
        "import com.google.gson.reflect.TypeToken;",
        "import com.fasterxml.jackson.databind.ObjectMapper;",
        "import com.fasterxml.jackson.core.type.TypeReference;",
        "import org.json.JSONObject;",
        "import java.io.IOException;",
        "import com.google.gson.JsonSyntaxException;",
        "import java.util.regex.Pattern;",
        "import java.math.BigInteger;",
        "import java.util.Arrays;",
        "import java.lang.Math;",
        "import java.util.HashSet;",
        "import java.util.Set;",
        "import com.google.gson.JsonElement;",
        "import java.util.HashMap;",
        "import com.google.gson.GsonBuilder;",
        "import java.util.AbstractMap.SimpleImmutableEntry;",
        "import java.lang.reflect.Type;",
        "import org.json.JSONArray;",
        "import java.util.StringTokenizer;",
        "import java.math.BigDecimal;",
        "import java.text.DecimalFormat;",
        "import java.util.Locale;",
        "import java.util.Scanner;",
        "import java.util.ArrayList;",
        "import java.util.InputMismatchException;",
        "import com.google.gson.JsonParser;",
        "import java.util.Collections;",
        "import java.util.Collections;",
        "import java.lang.Double;",
        "import java.util.LinkedHashSet;",
        "import java.lang.Integer;",
        "import java.util.Comparator;",
    ],
    "C"     : [
        "#include <stdio.h>",
        "#include <string.h>",
        "#include <time.h>",
        "#include <limits.h>",
        "#include <stdarg.h>",
        "#include <stdint.h>",
        # "#include <json-c/json.h>",
        "#include <math.h>",
        "#include <float.h>",
        "#include <stdbool.h>",
        # "#include <cjson/cJSON.h>",
        "#include <errno.h>",
        "#include <stddef.h>",
        "#include <stdlib.h>",
        "#include <stdio.h>",
        "#include <ctype.h>",
        # "#include <string>",
    ],
    "Haskell":[
    #     "import Data.List (words)",
    #     "import Data.Set (fromList)",
    #     "import Read (readMaybe)",
    #     "import Data.List (nub, sort, minimumBy)",
    #     "import Data.Text (replace)",
    #     "import Data.List (genericIndex, intercalate)",
    #     "import Data.List (sort, tails)",
    #     "import Data.List (filter, isPrefixOf)",
    #     "import Data.List (foldl')",
    #     "import Data.List (sortBy, intercalate, tails)",
    #     # "import Data.Set (Set)",
    #     "import Data.Maybe",
    #     "import Data.Ratio ((%))",
    #     "import Data.List (sort, isSubsequenceOf)",
    #     "import qualified Data.ByteString.Lazy.Char8 as B",
    #     "import Data.List (inits, intersperse)",
    #     "import Control.Exception (catch, Exception)",
    #     "import Data.Ord (comparing, Down(..))",
    #     "import Data.List (sort, elemIndex, intercalate)",
    #     "import Data.Aeson.Types (parseMaybe)",
    #     "import Data.List (intercalate, dropWhileEnd)",
    #     "import Data.Char (toLower, toUpper, isUpper)",
    #     "import Data.List (intercalate, words)",
    #     "import Data.List (nub, sort)",
    #     "import Numeric (showIntAtBase)",
    #     "import Data.Char (isSpace, isDigit, ord)",
    #     "import Data.Bits (shiftL, shiftR, (.|.), (.&.))",
    #     "import Data.Set (Set, setEmpty, insert, member, fromList)",
    #     "import Data.List (nub, intersperse)",
    #     "import Data.Ord (comparing, Down)",
    #     "import Data.Char (chr, ord, toUpper, toLower)",
    #     "import Data.Char (isDigit, isLetter)",
    #     "import qualified Data.ByteString.Lazy.Char8 as C",
    #     "import Data.Char (ord, toLower)",
    #     "import Control.Exception.Base (catch, SomeException)",
    #     "import Data.Set (fromList, size)",
    #     "import Data.List (nub, maximumBy, intercalate)",
    #     "import Data.List (zipWith, intercalate)",
    #     "import Data.String (strip)",
    #     "import Control.Exception (catch, SomeException(..))",
    #     "import Data.Char (isLetter, chr, ord)",
    #     "import Data.Char (toLower, toUpper)",
    #     "import Data.List (isInfixOf, isPrefixOf, intercalate)",
    #     "import Control.Applicative (liftA2)",
    #     "import Data.Text.Encoding (decodeUtf8)",
    #     "import Data.List (minimumBy)",
    #     "import Data.List (minimumBy, maximumBy, delete)",
    #     "import Data.Char (isPunctuation)",
    #     "import Data.List (foldl', intercalate)",
    #     "import Data.List (sort)",
    #     "import Data.List (isPrefixOf)",
    #     # "import Data.Vector (toList)",
    #     "import Data.List (foldl', isPrefixOf)",
    #     "import Data.Aeson (decodeStrict, FromJSON)",
    #     # "import Data.Char (digitToInt, fromEnum)",
    #     "import Control.Monad (forM_)",
    #     "import Data.Aeson (decode, encode)",
    #     "import Control.Exception (Exception)",
    #     "import Data.List (isInfixOf, intercalate)",
    #     # "import qualified Data.Map.Strict as Map",
    #     "import Data.List (tails)",
    #     "import Data.Text (pack, unpack)",
    #     "import Data.List (sort, intersect)",
    #     "import Data.List (maximumBy, minimumBy)",
    #     "import Data.Char (isLetter)",
    #     "import Data.Maybe (fromMaybe, listToMaybe, mapMaybe)",
    #     "import Data.List (nub, intercalate)",
    #     "import Data.List (intercalate, foldl')",
    #     "import Data.List (take, drop)",
    #     "import Data.List (genericTake, genericDrop)",
    #     "import Data.Bits ((.&.), shiftL, shiftR)",
    #     "import Numeric (readHex, readDec)",
    #     "import Control.Monad (unless)",
    #     "import Data.Char (isUpper, isLower)",
    #     "import Data.Aeson (decode, Value)",
    #     "import Data.List (sort, isPrefixOf, intercalate)",
    #     "import Data.Char (isDigit, isSpace)",
    #     "import Data.List (tail)",
    #     "import Data.Char (isLetter, toLower)",
    #     "import qualified Data.ByteString as BS",
    #     "import Data.Char (ord, chr)",
    #     "import Data.List (sortBy, intercalate, isPrefixOf)",
    #     "import Data.List (group, sort)",
    #     "import Data.List (intercalate)",
    #     "import Data.List (foldl', isPrefixOf, maximum)",
    #     "import Prelude",
    #     "import Data.Char (digitToInt, isDigit)",
    #     # "import Data.List (isSorted)",
    #     "import Control.Exception (catch, IOException)",
    #     "import Data.Text (unpack)",
    #     "import Data.List (nub, sort, intercalate)",
    #     "import Data.List (zipWith)",
    #     "import qualified Data.Ord as Ord",
    #     "import Control.Monad (liftM)",
    #     "import Control.Exception (catch, ErrorCall(..))",
    #     "import Data.ByteString.Lazy (pack)",
    #     "import Data.List (unfoldr)",
    #     "import Control.Monad (guard)",
    #     "import Data.Char (isLetter, isDigit)",
    #     "import Data.Ord (Down(..))",
    #     "import Numeric (readFloat)",
    #     "import Data.Aeson (decode, Value(..), FromJSON, parseJSON, withArray)",
    #     "import Data.List (intercalate, stripPrefix, isSuffixOf)",
    #     "import Data.List (sortBy, sort)",
    #     "import qualified Data.Text.IO as TIO",
    #     "import Data.Text.Read (double)",
    #     "import Data.Aeson (decode, Value, (.:))",
    #     "import Data.Maybe (isJust, fromMaybe)",
    #     "import Data.ByteString.Lazy (toStrict)",
    #     "import Data.Bits (xor)",
    #     "import Data.List (nub, sort, tails)",
    #     "import Data.List (intercalate, take)",
    #     # "import Data.Read (readMaybe)",
    #     "import Data.Aeson (decode)",
    #     "import Data.Function (on)",
    #     # "import Data.Set (Set, fromList, intersection)",
    #     "import Data.Bits (popCount)",
    #     "import Data.List (minimum, maximum, intercalate)",
    #     "import Control.Exception (throwIO)",
    #     "import Control.Exception (catch, throwIO, Exception)",
    #     "import Control.Exception (catch, throw, Exception)",
    #     "import Data.Aeson.Types (FromJSON)",
    #     "import Control.Applicative (optional)",
    #     "import qualified Data.Text.Read as TR",
    #     "import Data.Maybe (maybeToList)",
    #     "import Data.Aeson (decodeStrict)",
    #     "import Data.Text.Lazy.Encoding (encodeUtf8)",
    #     "import System.Environment (getArgs)",
    #     "import Data.List (sort, minimumBy, tails)",
    #     # "import Data.Set (Set, fromList)",
    #     # "import qualified Data.Map as Map",
    #     "import Data.List (nub, minimumBy)",
    #     # "import Data.List (sort, isSorted)",
    #     # "import qualified Data.ByteString.Lazy.UTF8 as B",
    #     # "import Data.List (minimum, maximum, (\\))",
    #     "import Control.Exception (SomeException, catch)",
    #     "import qualified Data.ByteString as B",
    #     "import Data.Math (round)",
    #     "import Data.List (foldl)",
    #     "import Data.Text (Text, isInfixOf)",
    #     "import Data.List (minimumBy, intersperse)",
    #     "import Data.List (intercalate)",
    #     "import qualified Data.ByteString.Lazy as BL",
    #     "import qualified Data.Maybe as Maybe",
    #     "import Data.Aeson (decode, encode, Value(..), (.:))",
    #     "import Data.List (intercalate, isPrefixOf, isSuffixOf, unfoldr)",
    #     "import Data.List (any)",
    #     "import Text.Read (readEither)",
    #     "import qualified Control.Exception as Exception",
    #     "import Data.List (isSubsequenceOf)",
    #     "import Data.List (nub, intercalate, isPrefixOf, tails)",
    #     "import Data.List (maximumBy)",
    #     "import ReadHelper (readList)",
    #     "import Data.List (intercalate, isPrefixOf, isSuffixOf, delete)",
    #     "import qualified Data.Text.Lazy.Encoding as TE",
    #     "import Data.List (isInfixOf)",
    #     "import Data.Char (ord)",
    #     "import Data.Char (isUpper, ord)",
    #     "import Control.Applicative (Alternative((<|>)))",
    #     "import Data.Text (pack, unpack, splitOn)",
    #     "import qualified Data.List",
    #     "import Data.List (intercalate, intersperse)",
    #     "import Data.Aeson (decode, Value(..))",
    #     "import Data.Vector (Vector)",
    #     "import Data.List (sortOn)",
    #     "import System.Exit (exitSuccess)",
    #     "import Data.Char (isAlpha, isDigit)",
    #     "import Data.IntMap.Strict (fromListWith, toList)",
    #     "import Data.List (filter)",
    #     "import Data.List (sort, isInfixOf)",
    #     "import Control.Exception (evaluate)",
    #     "import Data.List (intercalate, splitOn)",
    #     "import qualified Data.List as L",
    #     "import Data.List (stripSuffix)",
    #     "import Data.Char (toUpper, toLower, isLower)",
    #     "import Data.List (sort, elemIndex)",
    #     "import qualified Data.ByteString.Lazy.Char8 as BC",
    #     "import Data.List (nub, subsequences)",
    #     "import Data.List (isPrefixOf, intercalate)",
    #     "import Data.List (sort, nub, intersperse)",
    #     "import Data.List (minimum, elemIndex)",
    #     "import Data.List (sort, minimumBy)",
    #     "import Data.List.Split (splitOn)",
    #     "import Data.Char (isSpace, digitToInt)",
    #     "import Data.Aeson (decode, FromJSON)",
    #     "import Data.Functor ((&))",
    #     "import Control.Applicative (Alternative(..))",
    #     "import Numeric (readMaybe)",
    #     "import qualified Data.Char as Char",
    #     "import System.Exit (exitFailure, exitSuccess)",
    #     "import Data.List (sort, nub)",
    #     "import Data.Char (isAlpha)",
    #     "import Data.List (sort, isPrefixOf)",
    #     "import Data.Aeson (decode, Value, ToJSON, toJSON)",
    #     "import Data.List (sortBy, nub)",
    #     "import Data.Maybe (fromMaybe, mapMaybe)",
    #     "import Data.List (nub, maximumBy)",
    #     "import Data.Functor ((<&>))",
    #     "import Data.List (unpack)",
    #     "import Data.Char (isAlpha, isUpper, toLower, toUpper)",
    #     "import Control.Applicative ((<|>))",
    #     "import Data.List (genericIndex)",
    #     "import System.Exit",
    #     "import Data.Foldable (foldl')",
    #     "import Data.Maybe (fromMaybe, isNothing)",
    #     "import Data.Aeson (decode, Value(..), Number)",
    #     "import Data.Char (toEnum, fromEnum)",
    #     "import Numeric (showHex)",
    #     "import Data.ByteString.Lazy",
    #     "import Data.List (elemIndex, filter)",
    #     "import qualified Data.Aeson as Aeson",
    #     "import Data.List (rotate)",
    #     "import Math.NumberTheory.Primes (isPrime)",
    #     "import Data.List (genericReplicate, maximum)",
    #     "import Data.List (foldl', maximum)",
    #     "import Data.Char (isLetter, ord, chr)",
    #     "import Data.List (concat)",
    #     "import qualified Data.Set as Set",
    #     "import Data.List (length)",
    #     "import Data.Char (ord, chr, isUpper, isLower, toLower, toUpper)",
    #     "import Data.List (sort, sortOn)",
    #     "import Data.List (intercalate, stripPrefix)",
    #     "import System.Exit (die)",
    #     "import Data.List (genericZipWith)",
    #     "import Data.ByteString.Lazy.UTF8 as BLU (fromString)",
    #     "import Data.Aeson (decodeStrict, Value(..))",
    #     "import Data.Text.Encoding (encodeUtf8)",
    #     "import Data.List (sort, dropWhileEnd)",
    #     "import Data.List (sort, intercalate, isPrefixOf, isSuffixOf)",
    #     "import Data.Read (reads)",
    #     "import Data.Char",
    #     "import Data.List (find)",
    #     "import Data.List (elem)",
    #     "import System.Exit (exitWith, ExitCode(ExitFailure))",
    #     "import Data.Char (ord, isUpper, isLower)",
    #     "import Data.Text (strip, pack, unpack)",
    #     "import Data.List (foldl', sort)",
    #     "import Data.List (intersect)",
    #     "import Text.Read (readMaybe)",
    #     "import Data.ByteString.Lazy.Char8 (unpack)",
    #     "import Data.List (null)",
    #     "import Data.List (delete, minimum, maximum)",
    #     "import Data.List (intercalate, isInfixOf)",
    #     "import Data.Char (isUpper, isLower, isSpace)",
    #     "import Numeric (readInt)",
    #     "import Data.Char (ord, isUpper)",
    #     "import qualified Data.Text.Read as T",
    #     "import Data.Char (isLetter, toLower, toUpper)",
    #     "import Control.Applicative ((<*>))",
    #     "import Data.List (delete)",
    #     "import Data.List (intercalate, isPrefixOf, tails)",
    #     "import Control.Applicative (empty)",
    #     "import Data.List (listToMaybe)",
    #     "import Data.Readable",
    #     "import Data.Bool (bool)",
    #     "import Data.Rounding (round)",
    #     "import Data.Ord (comparing, minimumBy)",
    #     "import Data.List (unwords, words)",
    #     "import Control.Applicative",
    #     "import Data.Aeson (decode, encode, Value)",
    #     "import Control.Exception (Exception, throw)",
    #     "import Data.List (intercalate, unfoldr)",
    #     "import Data.List (intercalate, intersperse, nub)",
    #     "import Data.List (sort, group, intercalate)",
    #     "import Data.Aeson (decode, Value(..), (.:))",
    #     "import Data.Vector (Vector, fromList)",
    #     "import Data.Char (isDigit)",
    #     "import Data.List (unwords)",
    #     "import Data.Maybe (listToMaybe)",
    #     "import Data.List (nub, intersect)",
    #     "import Control.Exception (catch, SomeException)",
    #     "import Data.Aeson (decode, encode, FromJSON)",
    #     "import Data.Char (toLower, toUpper, isLower, isUpper)",
    #     "import Data.Text (unpack, replace)",
    #     "import Data.Char (toLower)",
    #     "import Data.Char (isUpper, isLower, toLower, toUpper)",
    #     "import Data.Read",
    #     "import Data.String (fromString)",
    #     "import Data.Aeson (encode)",
    #     "import Data.List (intercalate, sort)",
    #     "import Data.List (maximumBy, nub)",
    #     "import Control.Exception (Exception, throwIO)",
    #     "import Numeric (sqrt)",
    #     "import Data.Scientific (toBoundedInteger)",
    #     "import Data.List (tails, intercalate)",
    #     "import Data.List (unintersect)",
    #     "import Data.Text (Text, pack, isPrefixOf)",
    #     "import GHC.Generics (Generic)",
    #     "import qualified Data.List.Split as Split",
    #     "import Control.Exception (throw, Exception)",
    #     "import System.IO (hFlush, stdout)",
    #     "import Data.Maybe (listToMaybe, fromMaybe)",
    #     "import qualified Data.Text.Lazy as T",
    #     "import Data.List (intercalate, delete, sort)",
    #     "import Data.ByteString.Lazy.Char8 as B (pack)",
    #     "import Data.Bits (shiftR)",
    #     "import Data.ByteString.Lazy.Char8 (pack)",
    #     "import Data.Char (toLower, toUpper, isUpper, isLower)",
    #     "import Data.List (nub, sort, intersperse)",
    #     "import Data.List (words, intercalate)",
    #     "import Data.Ord (comparing)",
    #     "import Data.List (intercalate, maximum)",
    #     "import Data.List (take, intercalate)",
    #     "import Data.List (take)",
    #     "import Data.List (group, sort, intercalate)",
    #     "import Data.Maybe (isJust)",
    #     "import Data.List (subsequences, minimumBy)",
    #     "import Control.Monad (replicateM)",
    #     "import System.Exit (exitSuccess, exitWith, ExitCode(ExitFailure))",
    #     "import Data.Text",
    #     "import Data.Read (read)",
    #     "import System.Environment",
    #     "import Data.Maybe (isNothing, fromMaybe)",
    #     "import Control.Monad (when)",
    #     "import Data.List.Split (splitOn)",
    #     "import Data.Char (toUpper, toLower, isUpper)",
    #     "import Data.List (intercalate, isPrefixOf, isSuffixOf, stripPrefix, stripSuffix)",
    #     "import Data.Aeson (decode, Result(..))",
    #     "import Data.Bits (shiftL, (.&.))",
    #     "import Numeric (round)",
    #     "import Data.List (sort, intercalate, dropWhileEnd)",
    #     "import Numeric (readDec)",
    #     "import qualified Data.Text as T",
    #     "import Control.Exception",
    #     "import Data.List (sortBy, intersperse)",
    #     "import Data.List (sortBy)",
    #     "import Data.ByteString.Lazy.UTF8 (fromString)",
    #     "import Data.Char (isSpace)",
    #     "import Text.Read",
    #     "import Data.Char (isSpace, isDigit)",
    #     "import Data.Text.Encoding",
    #     "import qualified Data.ByteString.Char8 as BS",
    #     "import Data.List (sort, minimumBy, intersperse)",
    #     "import Data.Char (isDigit, digitToInt)",
    #     "import Data.Char (ord, isAlpha, isDigit)",
    #     "import Control.Monad (foldM)",
    #     "import Data.List (intercalate, filter)",
    #     "import System.IO (hPutStrLn, stderr)",
    #     "import Data.List (sort, sortBy, intercalate)",
    #     "import Data.Aeson.Types (Parser)",
    #     "import Data.List (sort, subsequences)",
    #     "import Data.Fixed (round)",
    #     "import Data.Char (toLower, toUpper, isLetter)",
    #     "import Data.List (genericLength)",
    #     "import Data.Abs (abs)",
    #     "import Data.List (sortBy, intercalate, filter)",
    #     "import Data.Readable (readable)",
    #     "import Data.Char (isLower)",
    #     "import qualified Data.Aeson as A",
    #     "import Data.List (genericMean)",
    #     "import qualified Safe",
    #     "import Data.Char (isDigit, ord)",
    #     "import Data.Text (pack, replace)",
    #     "import Data.Char (chr, ord)",
    #     "import Data.Text (strip, pack)",
    #     "import Data.Maybe (fromMaybe, listToMaybe)",
    #     "import Data.String.Utils (strip)",
    #     "import Data.List (maximum)",
    #     "import Data.Char (toUpper, toLower, isLower, isUpper)",
    #     "import Data.Char (toUpper, toLower)",
    #     "import Data.String.Utils (strip)",
    #     "import qualified Data.ByteString.Lazy as BSL",
    #     "import Control.Monad (mapM)",
    #     "import qualified Data.Text.Lazy as TL",
    #     "import Data.List (elemIndex)",
    #     "import Data.List (foldl', group, sort)",
    #     "import Data.Aeson (decode, Value, FromJSON)",
    #     "import Data.List (nub, minimumBy, maximumBy)",
    #     "import Data.List (minimum, maximum, intercalate, stripPrefix)",
    #     "import Data.Maybe (catMaybes)",
    #     "import Data.List (dropWhileEnd)",
    #     "import Data.List (sort, reverse)",
    #     "import Data.Char (ord, chr, isLower, isSpace)",
    #     "import Data.Char (isDigit, isAlpha)",
    #     "import Control.Monad (mapM_)",
    #     "import qualified Data.Vector as V",
    #     "import ReadP",
    #     "import Data.List (sort, intercalate, filter)",
    #     "import Data.List (minimum, maximum, delete)",
    #     "import Data.List (intercalate, isPrefixOf, isSuffixOf)",
    #     "import Data.Char (toUpper)",
    #     "import Data.Functor ((<$>))",
    #     "import Data.Text (Text)",
    #     "import Data.List (sort, minimumBy, elemIndex)",
    #     "import Data.List (group, sort, nub)",
    #     "import Data.Char (toLower, toUpper, isAlpha)",
    #     "import Data.Maybe (fromMaybe, isJust)",
    #     "import Data.List (inits, intercalate)",
    #     "import Data.List (sort, minimumBy, foldl')",
    #     "import Data.Char (toLower, toUpper, isUpper, isLower, ord, chr)",
    #     "import Data.Text (pack, unpack, stripPrefix, stripSuffix)",
    #     "import Control.Monad (forM)",
    #     "import Control.Monad (void)",
    #     "import Data.List (foldl', reverse)",
    #     "import Data.Time.Clock (getCurrentTime)",
    #     "import Data.List",
    #     "import Data.List (group)",
    #     "import System.Exit (exitFailure)",
    #     "import Data.Char (isLetter, toLower, ord)",
    #     "import Data.List (intercalate, sortBy)",
    #     "import Data.Map.Strict (Map)",
    #     "import Control.Monad",
    #     "import Data.Aeson (decode, Value(..), FromJSON)",
    #     "import Data.List (nub)",
    #     "import Data.Maybe (fromJust, fromMaybe)",
    #     "import Data.Text (isPrefixOf, pack)",
    #     "import Data.List (subsequences)",
    #     "import Data.List (sort, intercalate)",
    #     "import qualified Data.ByteString.Lazy as B",
    #     "import Data.Maybe (fromJust, fromMaybe, mapMaybe)",
    #     "import qualified Text.Read as Read",
    #     "import Control.Monad (join)",
    #     "import Data.List (genericTake)",
    #     "import Data.Typeable (Typeable)",
    #     "import Data.Aeson (decodeStrict, encode)",
    #     "import Data.List (sort, minimum, elemIndex)",
    #     "import Data.List (sort, intercalate, sortBy)",
    #     "import Control.Exception (catch, ArithException(..))",
    #     "import Data.Maybe (isNothing)",
    #     "import Data.List (sortBy, intercalate, words)",
    #     "import Control.Exception (try, SomeException)",
    #     "import Data.List (elemIndex, minimum)",
    #     "import Data.Aeson.Types (Array)",
    #     "import Data.Char (digitToInt)",
    #     "import Data.List (stripSuffix, isSuffixOf)",
    #     "import Data.List (isSuffixOf)",
    #     "import Numeric (showFFloat)",
    #     "import Data.Char (isAlpha, isUpper, isLower)",
    #     "import Data.List (intersect, sort)",
    #     "import Data.List (sort, sortBy)",
    #     "import Data.Aeson (decode, (.:))",
    #     "import Data.List (intercalate, delete)",
    #     "import Data.Fixed (CEILING)",
    #     "import Data.List (isPrefixOf, listToMaybe)",
    #     "import qualified Data.List as List",
    #     "import Data.Char (toLower, toUpper, isLetter, isLower)",
    #     "import Data.Either (isRight)",
    #     "import Data.List (intercalate, isPrefixOf, isInfixOf)",
    #     "import Data.Char (isDigit, intToDigit)",
    #     "import Data.Aeson (decode, Value(..), encode)",
    #     "import Data.Aeson (decode, Array)",
    #     "import Data.Text.Read (decimal)",
    #     "import Text.Printf",
    #     "import Data.Either (either)",
    #     "import Control.Exception (catch, ArithException)",
    #     "import Data.Text (pack, length)",
    #     "import qualified Data.ByteString.Lazy.Char8 as BS",
    #     "import Data.List (nub, maximum)",
    #     "import Data.List (tails, isPrefixOf)",
    #     "import Data.Set (intersection, fromList)",
    #     "import Data.List (isInfixOf, intersperse)",
    #     "import Data.Char (toUpper, toLower, ord, chr)",
    #     "import System.Exit (exitSuccess, exitFailure)",
    #     "import Data.List (filter, nub)",
    #     "import Data.Word (Word64)",
    #     "import Numeric (readHex)",
    #     "import qualified Data.Text.Encoding as T",
    #     "import System.Environment (getArgs)",
    #     "import Read (read)",
    #     "import Data.List (foldl, intersperse)",
    #     "import Control.Exception (catch, Throw, Exception)",
    #     "import Data.List (nub, sort)",
    #     "import Data.List (sort, intercalate, delete)",
    #     "import Data.List (words, unwords)",
    #     "import Data.Set (Set, fromList, equal)",
    #     "import Text.Printf (printf)",
    #     "import Data.Aeson.Types (Value)",
    #     "import Data.Char (isLetter, isLower)",
    #     "import Data.List (sort, sortOn, isSpace, intercalate)",
    #     "import Data.Set (fromList, Set)",
    #     "import Data.Char (isLetter, isAlpha)",
    #     "import Data.Array (Array, listArray, (!))",
    #     "import Data.List (intersect, nub)",
    #     "import Data.List (foldl', intercalate, delete)",
    #     "import Data.Attoparsec.Text (Parser, double, parseOnly)",
    #     "import Data.ByteString.Lazy (fromStrict)",
    #     "import Data.List (strip)",
    #     "import Data.List (sort, take, drop)",
    #     "import Data.List (foldl1')",
    #     "import Data.List (stripPrefix)",
    #     "import System.IO (hSetBuffering, BufferMode(NoBuffering), stdout)",
    #     "import Data.Either (fromRight)",
    #     "import Data.List (intersect, nub, sort)",
    #     "import Data.List (zip)",
    #     "import Data.List (isPrefixOf, isSuffixOf)",
    #     "import Data.List (stripPrefix, minimumBy)",
    #     "import Data.Char (isUpper)",
    #     "import Data.List (sum)",
    #     "import Data.Maybe (mapMaybe)",
    #     "import Data.List (reverse)",
    #     "import Data.List (nub, foldl')",
    #     "import qualified Data.Map as M",
    #     "import Data.List (nub, reverse)",
    #     "import Data.Int (Int64)",
    #     "import Data.ByteString.Char8 (pack)",
    #     "import Data.List (sort, intercalate, filter, sortBy)",
    #     "import Data.List (minimum, maximum)",
    #     "import Data.List (sortBy, intercalate)",
    #     "import Data.List (intercalate, isPrefixOf)",
    #     "import Data.Char (toLower, toUpper, ord, chr)",
    #     "import Data.Fixed (mod')",
    #     "import Data.Maybe (fromJust)",
    #     "import Data.Char (isAlpha, toUpper, toLower)",
    #     "import Data.Char (toUpper, toLower, isUpper, isLower)",
    #     "import Data.List (sort, minimumBy, isPrefixOf)",
    #     "import Data.List (nub, intercalate, stripPrefix)",
    #     "import Data.List (sort, intersperse)",
    #     "import Data.Maybe (fromMaybe)",
    #     "import Data.List (sort, foldl)",
    #     "import Data.List (reverse, tails)",
    #     "import Data.List (intersperse)",
    #     "import Data.String.Utils (replace)",
    #     "import Data.Aeson (decode, getJsonValue)",
    #     "import Data.List (sort, minimumBy, intersperse, tails)",
    #     "import Data.Aeson.Types (Value(..))",
    #     "import Data.List (intercalate, nub)",
    #     "import Data.Char (ord, isSpace)",
    #     "import Data.Aeson (decode, encode, Value(..))",
    #     "import Data.List (replicate)",
    #     "import Control.Exception (catch, throwIO)",
    #     "import Data.Text (pack)",
    #     "import Data.Text (strip)",
    #     "import Data.Char (intToDigit)",
    # ],

# "import Control.Applicative (Alternative(..), liftA2, optional, (<|>))",
"import Control.Exception (catch, Exception, throw, throwIO, SomeException(..), ArithException(..))",
"import Control.Monad (forM_, when, replicateM, join, void, mapM, mapM_)",
"import Data.Aeson (decode, encode, Value(..), FromJSON, ToJSON, (.:))",
"import Data.Aeson.Types (Parser, parseMaybe, getJsonValue, Array, Value)",
"import Data.Array (Array, listArray, (!))",
"import Data.Attoparsec.Text (Parser, double, parseOnly)",
"import Data.Bits (shiftL, shiftR, (.|.), (.&.), xor, popCount)",
"import Data.Bool (bool)",
"import Data.ByteString (ByteString)",
"import Data.ByteString.Char8 (pack)",
"import Data.ByteString.Lazy (ByteString, fromStrict, toStrict, pack)",
"import Data.ByteString.Lazy.Char8 (pack, unpack)",
"import Data.Char (toLower, toUpper, isUpper, isLower, isDigit, isSpace, isAlpha, isPunctuation, digitToInt, intToDigit, chr, ord)",
"import Data.Either (either, fromRight)",
"import Data.Fixed (CEILING, mod', round)",
"import Data.Foldable (foldl')",
"import Data.Function (on)",
"import Data.Int (Int64)",
"import Data.List (sort, sortBy, sortOn, nub, intercalate, filter, isInfixOf, isPrefixOf, isSuffixOf, genericIndex, genericTake, genericDrop, tails, inits, unfoldr, group, zipWith, maximumBy, minimumBy, delete, take, drop, rotate, intersect, reverse, concat, replicate, length, elemIndex, find, isSorted, sublist, null, zip, foldl, foldl1', genericReplicate, sum, stripPrefix, stripSuffix, genericLength, dropWhileEnd, strip)",
"import Data.List.Split (splitOn)",
"import Data.Map.Strict (Map)",
"import Data.Maybe (fromMaybe, listToMaybe, maybeToList, isJust, isNothing, mapMaybe, catMaybes, fromJust)",
"import Data.Ord (comparing, Down(..))",
"import Data.Ratio ((%))",
"import Data.Scientific (toBoundedInteger)",
"import Data.Set (Set, fromList, insert, member, size, intersection, equal)",
"import Data.String (fromString, strip)",
"import Data.Text (Text, pack, unpack, isPrefixOf, isInfixOf, replace, splitOn)",
"import Data.Text.Encoding (encodeUtf8, decodeUtf8)",
"import Data.Text.Read (decimal, double)",
"import Data.Time.Clock (getCurrentTime)",
"import Data.Vector (Vector, fromList, toList)",
"import Data.Word (Word64)",
"import Numeric (showIntAtBase, readHex, readDec, showFFloat, readFloat, readInt, showHex)",
"import Read (readMaybe)",
"import ReadP (readP_to_S)",
"import System.Environment (getArgs)",
"import System.Exit (exitSuccess, exitFailure, die, exitWith, ExitCode(ExitFailure))",
"import System.IO (hFlush, stdout, hPutStrLn, stderr, hSetBuffering, BufferMode(NoBuffering))",
"import Text.Printf (printf)",
"import Prelude",
"import qualified Data.ByteString as B",
"import qualified Data.ByteString.Lazy as BSL",
"import qualified Data.ByteString.Lazy.Char8 as BS",
"import qualified Data.List as L",
"import qualified Data.Map as M",
"import qualified Data.Map.Strict as Map",
"import qualified Data.Set as Set",
"import qualified Data.Text as T",
"import qualified Data.Text.Encoding as T",
"import qualified Data.Text.Lazy as TL",
"import qualified Data.Text.Lazy.Encoding as TE",
"import qualified Data.Text.Read as TR",
"import qualified Data.Vector as V",
"import qualified Data.ByteString.Lazy.UTF8 as B",
"import qualified Safe",
"import qualified Text.Read as Read",

    ],
    "Pascal":[
        # "uses SysUtils, ArrayUtils;",
        "SysUtils, Classes, fpjson, jsonparser;",
        "Math, SysUtils;",
        "crt;",
        "SysUtils, VarUtils;",
        "SysUtils, Variants;",
        "sysutils, math;",
        "sysutils, Classes;",
        "Crt;",
        "SysUtils, Classes, Variants;",
        "SysUtils, Math, Classes;",
        "sysutils;",
        "SysUtils;",
        "SysUtils, Classes, JSON;",
        "Math;",
        "SysUtils, Classes, StrUtils;",
        "sysutils, Classes, Math;",
        "SysUtils, fgl;",
        "SysUtils, strutils;",
        "crt, sysutils;",
        "SysUtils, JSON;",
        "sysutils, classes;",
        "SysUtils, Math;",
        "SysUtils, StrUtils;",
        "SysUtils, Variants, Classes;",
        "SysUtils, Math, StrUtils;",
        "SysUtils, Classes, Math;",
        "SysUtils, StrUtils, Math;",
        "SysUtils, fpjson, jsonparser;",
        "sysutils, classes, strutils;",
        "SysUtils, Classes;",
        "sysutils, Math;",
    ],
    "C#":[
        # "using System.Text;",
        "using System.Collections.Generic;",
        "using System.Numerics;",
        # "using System.Text.Json;",
        "using System.Web.Script.Serialization;",
        "using System.Runtime.Serialization.Json;",
        "using System.Text.Json.Nodes;",
        "using System.IO;",
        "using System.Linq;",
        # "using Newtonsoft.Json;",
        "using System.Text.RegularExpressions;",
        "using System.Linq;",
        "using Newtonsoft.Json;",
        "using System.Text.Json.Serialization;",
        "using System.Collections;",
        "using System.Globalization;",
        "using System;",
        "using System.Text.Json;",
    ],
}

def removeBackticks(response):
    lines = response.splitlines()
    processed_lines = []
    skip_line = False
    skip_Next_line = False
    bracketRemovalNext = False
    classFound = False
    for line in lines:
        if '```' in line:
            if not skip_line:
                skip_line = True  # Start skipping lines after the first occurrence of backticks
            continue  # Skip the current line containing backticks

        # removing imports
        if "using" in line: continue
        if "#include" in line: continue
        if "import" in line: continue
        if "uses" in line: 
            skip_Next_line = True
            continue
        if skip_Next_line: 
            skip_Next_line = False
            continue
        # removing classes
        if "class" in line:
            classFound = True
            if not "{" in line:
                bracketRemovalNext = True
            continue
        if bracketRemovalNext:
            bracketRemovalNext = False
            continue
            
        
        if skip_line:
            # If we are skipping lines, stop once we encounter another line with backticks
            if '```' in line:
                break
            else:            
                processed_lines.append(line)
        
    if classFound:
        processed_lines = processed_lines[:-1]
    return '\n'.join(processed_lines).strip()


def addProgrammStructure(functions, Language):
    program = ""
    if Language == "Java":
        program = addJavaStructure(functions)
    elif Language == "Python":
        program = addPythonStructure(functions)
    elif Language == "Javascript":
        program = addJavascriptStructure(functions)
    elif Language == "C++":
        program = addCPPStructure(functions)
    elif Language == "Haskell":
        program = addHaskellStructure(functions)
    elif Language == "Pascal":
        program = addPascalStructure(functions)
    elif Language == "C#":
        program = addCScharfStructure(functions)
    elif Language == "C":
        program = addCStructure(functions)
    return program


def addJavaStructure(functions):
    functionsString = "\n".join(functions)
    code = f"""
public class Solution {"{"}
     {functionsString}
{"}"}"""
    imports = "\n".join(IMPORT_HELPER["Java"]) + "\n"
    code = imports + code
    return code

def addPythonStructure(functions):
    functionsString = "\n".join(functions)
    imports = "\n".join(IMPORT_HELPER["python"]) + "\n"
    code = imports + functionsString
    return code

def addJavascriptStructure(functions):
    functionsString = "\n".join(functions)
    # imports = "\n".join(IMPORT_HELPER["Javascript"]) + "\n"
    code = functionsString
    return code

def addCPPStructure(functions):
    functionsString = "\n".join(functions)
    imports = "\n".join(IMPORT_HELPER["C++"]) + "\n"
    code = imports + functionsString
    return code


def addHaskellStructure(functions):
    functionsString = "\n".join(functions)
    imports = "\n".join(IMPORT_HELPER["Haskell"]) + "\n"
    code = imports + functionsString
    return code

def addPascalStructure(functions):
    programmString = "program FixSpaces; \n uses\n"
    functionsString = "\n".join(functions)
    imports = " ".join(IMPORT_HELPER["Pascal"]) + "\n"
    code = programmString + imports  + functionsString
    return code


def addCScharfStructure(functions):
    functionsString = "\n".join(functions)
    code = f"""
 class Solution {"{"}
     {functionsString}
{"}"}"""
    imports = "\n".join(IMPORT_HELPER["C#"]) + "\n"
    code = imports + code
    return code

def addCStructure(functions):
    functionsString = "\n".join(functions)
    imports = "\n".join(IMPORT_HELPER["C"]) + "\n"
    code = imports + functionsString
    return code
